# Generated by Django 6.1 on 2026-08-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('users', '0002_remove_profile_branch_alter_profile_role_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='awaiting_approval',
        ),
        migrations.AddField(
            model_name='processtype',
            name='approval_level',
            field=models.CharField(choices=[('none', 'No approval needed'), ('lead', 'Team Lead only'), ('lead_head', 'Team Lead, then Department Head')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_stage',
            field=models.CharField(choices=[('draft', 'Not submitted'), ('lead_review', 'With Team Lead'), ('head_review', 'With Department Head'), ('approved', 'Approved'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.team'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('decision', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='portal.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
