# Generated by Django 6.1 on 2026-08-09 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Tasks of this type need a sign-off before they count as completed.'),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='awaiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
