# Generated by Django 6.1 on 2026-08-15 03:04

from django.db import migrations, models


def freeze_existing(apps, schema_editor):
    """Give tasks raised before snapshots existed the checklist they were
    working to, so nothing changes underneath them retrospectively."""
    Task = apps.get_model('portal', 'Task')
    for task in Task.objects.select_related('process_type').iterator():
        if not task.checklist_snapshot:
            task.checklist_snapshot = list(task.process_type.checklist or [])
            task.save(update_fields=['checklist_snapshot'])


def unfreeze(apps, schema_editor):
    """Nothing to undo - the column goes away with the reverse AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_task_status_remove_escalation_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checklist_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(freeze_existing, unfreeze),
    ]
