# Generated by Django 6.1 on 2026-08-16 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_task_archived_at_task_archived_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='requires_authorisation',
            field=models.BooleanField(default=False, help_text='Tick for work that must be permitted before it starts, not just checked after.'),
        ),
        migrations.AddField(
            model_name='task',
            name='authorised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='approval_stage',
            field=models.CharField(choices=[('auth_lead', 'Awaiting Team Lead permission'), ('auth_head', 'Awaiting Department Head permission'), ('draft', 'Not submitted'), ('lead_review', 'With Team Lead'), ('head_review', 'With Department Head'), ('approved', 'Approved'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
    ]
