# Generated by Django 6.1 on 2026-08-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminders_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
