# Generated by Django 6.1 on 2026-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_task_final_warning_at_task_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
