# Generated by Django 6.1 on 2026-08-17 14:54

from django.db import migrations, models


def signoff_for_everything(apps, schema_editor):
    """Processes that needed no approval now need the Team Lead.

    They are the ones where staff closed their own work, which is what this
    change exists to stop.
    """
    ProcessType = apps.get_model('portal', 'ProcessType')
    ProcessType.objects.filter(approval_level='none').update(approval_level='lead')


def back_to_none(apps, schema_editor):
    """No way to tell which ones were 'none' before, so this only makes the
    column valid again for the old choices. Nothing is restored."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_task_stage_since'),
    ]

    operations = [
        migrations.RunPython(signoff_for_everything, back_to_none),
        migrations.AlterField(
            model_name='processtype',
            name='approval_level',
            field=models.CharField(choices=[('lead', 'Team Lead only'), ('head', 'Department Head only'), ('lead_head', 'Team Lead, then Department Head')], default='lead', max_length=20),
        ),
    ]
