# Generated by Django 6.1 on 2026-08-14 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_branch_alter_profile_role_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'profile__role__in': ['team_lead', 'dept_head', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='teams_led', to=settings.AUTH_USER_MODEL),
        ),
    ]
