# Generated by Django 6.1 on 2026-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
