# Generated by Django 6.1 on 2026-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_invite_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
