# Generated by Django 6.1 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_approval_digest_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_head', 'Department Head'), ('team_lead', 'Team Lead'), ('staff', 'Operations Staff'), ('auditor', 'Auditor')], default='staff', max_length=20),
        ),
    ]
