"""
Django settings for Operations_Portal project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets and per-machine configuration live in .env, which is gitignored.
# See .env.example for every key this project reads.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    """Comma-separated env value -> list, ignoring blanks and stray spaces."""
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

INSECURE_DEV_KEY = 'django-insecure-%4uy2xw7yve5r$#@9oniicqrbrtk$-k_ugw#_09n#kxrmp$xew'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or INSECURE_DEV_KEY

if not DEBUG and SECRET_KEY == INSECURE_DEV_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. Generate one with:\n'
        '  python -c "from django.core.management.utils import get_random_secret_key; '
        'print(get_random_secret_key())"'
    )

# Hostnames this site answers to, e.g. "portal.dash-mfb.com,10.0.1.14".
# Django refuses any request whose Host header isn't listed.
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')

# Required once the portal is served over HTTPS, or POSTs get rejected.
# Full origins including the scheme: "https://portal.dash-mfb.com".
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    # 'portal.apps.PortalConfig',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Serves everything under STATIC_ROOT. Must sit directly after the
    # security middleware. Does not touch MEDIA_ROOT, which is the point.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Last, so the messages framework above it has already prepared the
    # request. Converts uncaught ValidationErrors into a flash message.
    'portal.middleware.FriendlyValidationErrorMiddleware',
]

ROOT_URLCONF = 'Operations_Portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portal.context_processors.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'Operations_Portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Defaults to the local SQLite file. For production set DB_ENGINE to
# 'django.db.backends.postgresql' and fill in the rest - SQLite does not cope
# with concurrent writers.
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE.endswith('sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ.get('DB_NAME') or BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ.get('DB_NAME', ''),
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', ''),
            'PORT': os.environ.get('DB_PORT', ''),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# People sign in with their corporate email address only - usernames are not
# accepted. EmailBackend subclasses ModelBackend, so permission checks still
# work; adding django.contrib.auth.backends.ModelBackend back here would
# silently re-enable username logins.
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
]

LOGIN_URL = 'portal-login'
LOGIN_REDIRECT_URL = 'portal-home'
LOGOUT_REDIRECT_URL = 'portal-login'

# Password-reset email, sent through the Microsoft Graph API.
# Office 365 usually has SMTP AUTH switched off, so a client-credentials app
# registration is used instead of Django's SMTP backend. Credentials come from
# .env; see users/email_backends.py.
MS_GRAPH_TENANT_ID = os.environ.get('MS_GRAPH_TENANT_ID', '')
MS_GRAPH_CLIENT_ID = os.environ.get('MS_GRAPH_CLIENT_ID', '')
MS_GRAPH_CLIENT_SECRET = os.environ.get('MS_GRAPH_CLIENT_SECRET', '')
MS_GRAPH_SENDER = os.environ.get('MS_GRAPH_SENDER', '')

if MS_GRAPH_TENANT_ID and MS_GRAPH_CLIENT_ID and MS_GRAPH_CLIENT_SECRET and MS_GRAPH_SENDER:
    EMAIL_BACKEND = 'users.email_backends.MicrosoftGraphEmailBackend'
    DEFAULT_FROM_EMAIL = MS_GRAPH_SENDER
else:
    # No Graph credentials configured - print the email to the runserver
    # terminal instead, so password reset still works locally.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Dash MFB Operations Portal <no-reply@dash-mfb.com>'

PASSWORD_RESET_TIMEOUT = 60 * 60 * 3

# Deadline reminders, sent by the send_task_reminders management command.
#
# The command has no HTTP request to work out the site address from, so the
# links in the emails are built from SITE_URL. Get this wrong and every
# reminder points somewhere useless.
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000').rstrip('/')

# Email somebody the moment work is assigned to them. Sent from the request
# rather than the cron round: being told promptly is the whole point.
ASSIGNMENT_EMAILS_ENABLED = env_bool('ASSIGNMENT_EMAILS_ENABLED', True)

REMINDERS_ENABLED = env_bool('REMINDERS_ENABLED', True)

# How the chasing is paced.
#
#   milestones  fractions of this task's own deadline, so a 2 hour job and a
#               2 day job each get the same small number of emails
#   interval    a fixed clock, the same for every task whatever its target
#
# Milestones are the default because a fixed clock sends far too much on a
# long task: every 30 minutes over a 24 hour target is 48 emails, which people
# filter to junk, taking the final warning with it.
REMINDER_MODE = os.environ.get('REMINDER_MODE', 'milestones').strip().lower()

if REMINDER_MODE not in ('milestones', 'interval'):
    raise ImproperlyConfigured(
        f'REMINDER_MODE must be "milestones" or "interval", got "{REMINDER_MODE}".'
    )

# Percentages of the way to the deadline at which to send. "50,80" on a 24 hour
# task means one email after 12 hours and another after 19 hours 12 minutes.
REMINDER_MILESTONES = sorted(
    int(part) for part in env_list('REMINDER_MILESTONES', '50,80')
)

# Used only when REMINDER_MODE is "interval".
REMINDER_EVERY_MINUTES = int(os.environ.get('REMINDER_EVERY_MINUTES', '30'))

# The one-off last call, sent once when this many minutes remain.
REMINDER_FINAL_MINUTES = int(os.environ.get('REMINDER_FINAL_MINUTES', '15'))

# Once a task is late, email is not what fixes it, so slow right down. Daily.
REMINDER_OVERDUE_EVERY_MINUTES = int(os.environ.get('REMINDER_OVERDUE_EVERY_MINUTES', '1440'))

# Backstop for "interval" mode, so a task nobody ever touches does not email
# someone forever. Milestone mode is self-limiting.
REMINDER_MAX_PER_TASK = int(os.environ.get('REMINDER_MAX_PER_TASK', '8'))


def env_hours(name, default):
    """"8-18" -> (8, 18). Equal values mean no quiet period at all."""
    raw = os.environ.get(name, default)
    try:
        start, end = (int(part) for part in raw.split('-', 1))
    except ValueError:
        raise ImproperlyConfigured(f'{name} must look like "8-18", got "{raw}".')
    if not (0 <= start <= 24 and 0 <= end <= 24):
        raise ImproperlyConfigured(f'{name} hours must be between 0 and 24, got "{raw}".')
    return start, end


# Routine reminders are held back outside these hours, so a deadline running
# through the night does not email anyone at 3am. Set to "0-0" to send at any
# hour. The final warning ignores this - it is the whole point of it.
REMINDER_HOURS = env_hours('REMINDER_HOURS', '8-18')


# Approval digests: one email per manager listing the work waiting on their
# decision, sent by the send_approval_digests management command. One email
# each rather than one per task, or a Department Head covering several teams
# would be buried. REMINDER_HOURS applies to these too.
APPROVAL_DIGESTS_ENABLED = env_bool('APPROVAL_DIGESTS_ENABLED', True)

# Shortest gap between two digests to the same person, so a busy morning does
# not produce an email every time a task is raised.
APPROVAL_DIGEST_MIN_GAP_MINUTES = int(os.environ.get('APPROVAL_DIGEST_MIN_GAP_MINUTES', '60'))

# How often to send again when nothing new has arrived but work is still
# sitting there unactioned.
APPROVAL_DIGEST_EVERY_MINUTES = int(os.environ.get('APPROVAL_DIGEST_EVERY_MINUTES', '240'))

# Invites last longer than a reset - a new starter may not check mail same day.
INVITE_LINK_TIMEOUT = 7 * 24 * 60 * 60


# Rows per page on every list. Small enough that a queue stays scannable.
PAGE_SIZE = int(os.environ.get('PAGE_SIZE', '25'))

SESSION_COOKIE_AGE = 15 * 60
SESSION_SAVE_EVERY_REQUEST = True


# HTTPS and cookie security
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# These default to "on whenever DEBUG is off", so a production deploy is
# secure without setting anything. The env vars exist to override that - for
# example turning the SSL redirect off while TLS is still being set up.

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Behind a load balancer or reverse proxy, this header is the only way Django
# knows the original request was HTTPS. Without it SECURE_SSL_REDIRECT loops
# forever. Only switch on when the proxy is trusted to set the header itself.
if env_bool('DJANGO_USE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HSTS makes browsers refuse plain HTTP for this domain, and they remember it
# for the full duration. Start small (3600), raise to 31536000 once HTTPS is
# confirmed on every subdomain - it cannot be taken back quickly.
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Timestamps are stored in UTC (USE_TZ below). This is only the zone
# they are rendered in - and the one REMINDER_HOURS is judged against, so a 
# wrong value here silently shifts the quiet period for reminder emails.
# 
# Africa/Lagos is the default because that is where the department sits; a
# deployment elsewhere overrides it with DJANGO_TIME_ZONE.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Africa/Lagos').strip()

# A typo would otherwise surface as a ZoneInfoNotFoundError on the first page
# that renders a timestamp, which reads as a broken view rather than a bad
# .env. Fail at startup instead, the way REMINDER_MODE and REMINDER_HOURS do.
try:
    ZoneInfo(TIME_ZONE)
except (ZoneInfoNotFoundError, ValueError) as exc:
    raise ImproperlyConfigured(
        f'DJANGO_TIME_ZONE must be an IANA zone name such as "Africa/Lagos", '
        f'got "{TIME_ZONE}".'
    ) from exc

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Uploaded task attachments.
#
# There is deliberately NO MEDIA_URL route and nothing serves this directory
# directly. Attachments hold customer documents, so every download goes
# through portal.views.attachment_download, which checks who is asking.
# Do not add static()/MEDIA_URL serving for this path.
MEDIA_ROOT = BASE_DIR / 'mediafiles'

MAX_UPLOAD_BYTES = int(os.environ.get('MAX_UPLOAD_MB', '10')) * 1024 * 1024
ALLOWED_UPLOAD_SUFFIXES = {
    '.png', '.jpg', '.jpeg', '.gif', '.webp', '.heic',
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.csv', '.txt',
}

STATIC_URL = 'static/'

# Appended to the stylesheet link so a changed CSS file is never served from
# the browser cache. Bump when you edit the CSS.
ASSET_VERSION = '14'

# Where `manage.py collectstatic` writes to. Run it on every deploy.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Gzip and brotli each collected file so WhiteNoise can serve the compressed
# copy. Deliberately NOT the Manifest variant: fingerprinting would mean any
# code path that renders a template needs collectstatic to have run first,
# which makes the test suite depend on a build step and turns one uncollected
# file into a 500. ASSET_VERSION above already busts caches on a CSS change.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
